### ISSUE TITLE
[GitHub Actions] todo list to improve

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1397]
I have attempted to improve the workflow but without much success.
I'll list the tasks to build the entire project only with GH.
I moved this work on the [winbuild](https://github.com/mcallegari/qlcplus/tree/winbuild) branch

Linux:
- [X] ~~remove ccache (being a VM it's useless)~~
- [X] fix variables parsing (awk was not really working)
- [X] make a release version
- [X] remove relocation workaround
- [x] test units fail with xvfb 
- [x] fix appimage not including any system library
- [ ] figure out why ccache hits are 0%
- [ ] figure out why coverage target performs test units

Windows:
- [X] re-enable windows build
- [X] use dynamic Qt libraries (not even sure QLC+ builds with static libs)
- [x] ~~udmx plugin fails to find libusb-1.0 even though it's there~~
- [x] ~~installation fails cause of webaccess resources (wtf)~~
- [x] ~~store windows artifacts~~

**Comment by mcallegari** [comment]
@hjtappe not sure what happened but it's failing on master too now :cry: 
As if something has changed on xvfb since your PR was merged.
I doubt [this](https://github.com/mcallegari/qlcplus/pull/1386) is the cause.

**Comment by hjtappe** [comment]
@mcallegari the ccache in fact stores the cache outside the VM and improves the run time and thus the development cycle by a certain time.
I'll take a look at the xvfb issue later this week. The tests were running successfully with Werror at one point in time before I separated the merge requests.

**Comment by hjtappe** [comment]
I have merge the master on my side and can reproduce the error
`qt.qpa.plugin could not load the qt platform plugin xcb in even though it was found`

The issue is discussed e.g. here:
https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/15

It might be caused by some library or dependency change or an update within QT.

My recommended action: You can disable the "Test Load AppImage". It is not so important and is only to try if the application loads, but it is an incomplete test anyways and works only with qt5-qml and does not cover dynamically linked binaries.

We can re-enable and investigate this deeper if we see it necessary again.

Also, I would propose that you move the "Test" target right after the "Build" target, so errors in the development tests are run before the creation of the AppImage.

**Comment by mcallegari** [comment]
It's not just the appimage test failing.
In winbuild branch I have fixed it by using the offscreen QPA plugin
https://github.com/mcallegari/qlcplus/blob/winbuild/.github/workflows/build.yml#L216
Once that was fixed, I started to see the same error on test units too.
So I tried to apply the same fix and discovered that not all the test units support the --platform parameter, which is super awkward (I tried it also on my PC and I can confirm it...without an explanation)

There are so many unexpected results on GH servers so it takes an enormous amount of time to figure everything out

**Comment by kingpin1905** [comment]
Hello! I feel bad for writing here as it is a bit off-topic.
I have been using your amazing software for a few years now and it's been great. I'm a computer science student and I've been learning web development for a few months now. I always wanted to help this project, so if you ever want a website redesign, I would love to help with that.
Sorry for bothering you. Keep up your amazing work!

**Comment by hjtappe** [comment]
I just triggered a build on the previously passing branch which introduced the GH actions. It now fails too with no change (one character in a build.yml comment changed to trigger the build). So there must have been a change in the environments which we pull.
I'm going to investigate more.

**Comment by hjtappe** [comment]
Linux todos:

- remove ccache (being a VM it's useless)
  - this in fact reports in my builds in the "Post Setup ccache" step: cache hit rate 99.42 %. Please check if that is also the case in the master build. It improves times significantly.
- fix variables parsing (awk was not really working)
  - Hm, I didn't notice, but I trust you will find a solution. Let me know what detail you found if I could help.
- remove relocation workaround
  - it is taken from the `create-appimage.sh` script. You might want to also update that one.
- test units fail with xvfb
  - see  #1399 for one way to make it work again.

**Comment by mcallegari** [comment]
I have re-enabled ccache on winbuild branch too.

AWK parsing. This doesn't work:
`echo "CI_BRANCH=$(echo $GITHUB_REF | awk 'BEGIN {FS=\"/\"}; {print $3}')" >> $GITHUB_ENV`
with error:
```
awk: cmd. line:1: BEGIN {FS=\"/\"}; {print $3}
awk: cmd. line:1:           ^ backslash not last character on line
```
This works:
`echo "CI_BRANCH=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV`

**Comment by mcallegari** [comment]
I think I might know what relocation error is: the resulting appimage(s) don't include any system library!
So there's no Qt as well. It probably tries to hook to your system Qt libs and find version differences, thus a relocation issue. Maybe that's it...I will investigate why this is happening.

**Comment by mcallegari** [comment]
@hjtappe hi, I've finally sorted out the creation of appimages. Now qt5 and qmlui artifacts are both working as expected.
I still need to understand why ccache is not having any effect. I see hits at 0%. Do you have any clue?

**Comment by hjtappe** [comment]
Great to hear that appImages now work as expected. Thanks for fixing that.

I have downloaded both logs, cleaned away timestamp differences and see the following differences / similarities.
The actions configuration is the same between master and my merged master. Still, the results are different.
- on my side, the apt cache does not seem to be found, even though it is persisted.
- on your side, the list of sources files is much larger when installing the apt packages. There is a minor difference in the ubuntu version that is used, but that does not justify the changes.
- For ccache (line 1459 ff., your log), it is found in your log, but not in mine (which might be cause due t the fact that I don't build the master very often).
- in line 1510, the cache stats are cleared in both runs.
- in line 14179, the stats look different between the runs. Even though both have been cleared, your stats show zeros, mine don't, even though both seem to have applied ccache (because the cache size indicate that it is used).

The reason for these differences does not yet jump into my eyes.
I suspect some kind of timing or cache effect as the cause, but I am puzzled too. I might delete all caches and start over from a clean actions space to see if that changes anything.

[qlcplus-hjtappe.log](https://github.com/mcallegari/qlcplus/files/11000614/qlcplus-hjtappe.log)
[qlcplus-mcallegari.log](https://github.com/mcallegari/qlcplus/files/11000616/qlcplus-mcallegari.log)

**Comment by mcallegari** [comment]
@hjtappe I found this
https://stackoverflow.com/questions/63548721/ccache-hit-rate-0-00-in-github-actions-ci
Gonna try to increase the cache size

**Comment by mcallegari** [comment]
Good news!
After a lot of effort, we finally have automated Windows builds with cmake.
For now it's on a branch, but will be merged soon.
Therefore closing this
